train:
  - _target_: pangaea.engine.data_preprocessor.BandFilter
  - _target_: pangaea.engine.data_preprocessor.ResizeToEncoder
  - _target_: pangaea.engine.data_preprocessor.NormalizeMeanStd
  - _target_: pangaea.engine.data_preprocessor.BandPadding

test:
  - _target_: pangaea.engine.data_preprocessor.BandFilter
  - _target_: pangaea.engine.data_preprocessor.ResizeToEncoder
    resize_target: False
  - _target_: pangaea.engine.data_preprocessor.NormalizeMeanStd
  - _target_: pangaea.engine.data_preprocessor.BandPadding