_target_: pangaea.encoders.croma_encoder.CROMA_SAR_Encoder

#---------Model Specific Arguments--------

#---------Required Arguments--------
#model weight
model_name: croma_sar
encoder_weights: ./pretrained_models/CROMA_large.pt
download_url: https://huggingface.co/antofuller/CROMA/resolve/main/CROMA_large.pt

#transformer
input_size: 120
patch_size: 8
embed_dim: 1024
depth: 24
num_heads: 16
has_cls_token: False

#features
pyramid_features: False
multi_temporal: False
multi_temporal_fusion: False
naive_multi_forward_mode: 'loop'

#channels
input_bands:
  sar:
    - VV
    - VH
output_layers:
  - 3
  - 5
  - 7
  - 11
output_dim: 1024