_target_: pangaea.encoders.gfmswin_encoder.GFMSwin_Encoder

#---------Model Specific Arguments--------

in_chans: 3
depths_per_layer:
  - 2
  - 2
  - 18
  - 2
num_heads_per_layer:
  - 4
  - 8
  - 16
  - 32
window_size: 6
mlp_ratio: 4
#only_output_last: True


#---------Required Arguments--------
model_name: gfm_swin
encoder_weights: ./pretrained_models/gfm.pth
download_url: null

#transformer
input_size: 192 # fixed to 192 to avoid interpolation in checkpoints which leads to drop in performance
patch_size: 4
embed_dim: 128
depth: 4
num_heads: null
has_cls_token: False

#features
pyramid_features: True
multi_temporal: False
multi_temporal_fusion: False
naive_multi_forward_mode: 'loop'

#channels
input_bands:
  optical:
    - B4
    - B3
    - B2

output_layers:
  - 0
  - 1
  - 2
  - 3

output_dim:
  - 256
  - 512
  - 1024
  - 1024










