_target_: pangaea.encoders.prithvi_encoder.Prithvi_Encoder

#---------Model Specific Arguments--------

num_frames: ${dataset.multi_temporal}
tubelet_size: 1
mlp_ratio: 4
norm_layer:
  _target_: hydra.utils.get_class
  path: torch.nn.LayerNorm

#---------Required Arguments--------

#model weight
model_name: Prithvi
encoder_weights: ./pretrained_models/Prithvi_100M.pt
download_url: https://huggingface.co/ibm-nasa-geospatial/Prithvi-100M/resolve/main/Prithvi_100M.pt?download=true

#transformer
embed_dim: 768
input_size: 224
patch_size: 16
num_heads: 12
depth: 12
has_cls_token: True

#features
pyramid_features: False
multi_temporal: True
multi_temporal_fusion: False
naive_multi_forward_mode: 'loop'

#channels
input_bands:
  optical:
    - B2
    - B3
    - B4
    - B8A
    - B11
    - B12

output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 768
