_target_: pangaea.encoders.remoteclip_encoder.RemoteCLIP_Encoder

#---------Model Specific Arguments--------

mlp_ratio: 4.0

#---------Required Arguments--------

#model weight
model_name: remoteclip
encoder_weights: ./pretrained_models/RemoteCLIP-ViT-B-32.pt
download_url: https://huggingface.co/chendelong/RemoteCLIP/resolve/main/RemoteCLIP-ViT-B-32.pt

#transformer
embed_dim: 768
input_size: 224
depth: 12
num_heads: 12
patch_size: 32
has_cls_token: True

#features
pyramid_features: False
multi_temporal: False
multi_temporal_fusion: False
naive_multi_forward_mode: 'loop'

#channels
input_bands:
  optical:
    - B4
    - B3
    - B2

output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 768