_target_: pangaea.encoders.spectralgpt_encoder.SpectralGPT_Encoder
#---------Model Specific Arguments--------
t_patch_size: 3
mlp_ratio: 4

#---------Required Arguments--------
#model
model_name: SpectralGPT
encoder_weights: ./pretrained_models/SpectralGPT+.pth
download_url: https://zenodo.org/records/8412455/files/SpectralGPT+.pth

#transformer
embed_dim: 768
input_size: 128
depth: 12
num_heads: 12
patch_size: 8
has_cls_token: False

#features
pyramid_features: False
multi_temporal: False
multi_temporal_fusion: False
naive_multi_forward_mode: 'loop'

#channels
input_bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B11
    - B12

output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 3072   # 768 * (in_chans / t_patch_size)

