_target_:  pangaea.encoders.ssl4eo_mae_encoder.SSL4EO_MAE_SAR_Encoder
#---------Model Specific Arguments--------

mlp_ratio: 4

#---------Required Arguments--------
model_name: ssl4eo_mae_sar
encoder_weights: ./pretrained_models/B2_vits16_mae_ep99.pth
download_url: https://huggingface.co/wangyi111/SSL4EO-S12/resolve/main/B2_vits16_mae_ep99.pth

#transformer
embed_dim: 384
input_size: 224
patch_size: 16
num_heads: 6
depth: 12
has_cls_token: True

#features
pyramid_features: False
multi_temporal: False
multi_temporal_fusion: False
naive_multi_forward_mode: 'loop'

input_bands:
  sar:
    - VV
    - VH

output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 384