_target_:  pangaea.encoders.ssl4eo_mae_encoder.SSL4EO_MAE_OPTICAL_Encoder
#---------Model Specific Arguments--------

mlp_ratio: 4

#---------Required Arguments--------
model_name: ssl4eo_mae_optical
encoder_weights: ./pretrained_models/B13_vits16_mae_0099_ckpt.pth
download_url: https://drive.google.com/uc?id=1LREGuI6w7Gq6Xm0jFQdxxtp8QkmLvJWk&export=download&confirm=yes

#transformer
embed_dim: 384
input_size: 224
patch_size: 16
num_heads: 6
depth: 12
has_cls_token: True

#features
pyramid_features: False
multi_temporal: False
multi_temporal_fusion: False
naive_multi_forward_mode: 'loop'

#channels
input_bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B10
    - B11
    - B12

output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 384